function [text] = languagetransfer(currentLanguage, currentBlockNumber, n_blocks)

if currentLanguage == "English"

    line1 = ['\n Welcome to this experiment.'...
        '\n\n During the experiment you will see images for 3 seconds each.'...
        '\n Some of the images are shown multiple times. Your task is to decide if the image ' ...
        '\n presented to you is a "new image" (has not been shown to you before) '...
        '\n or old image (has been shown before). Please press the "4"-key with '...
        '\n your right index finger if you think the image presented to you is a ' ...
        '\n "new image". Press the "5"-key with your right middle finger if ' ...
        '\n you think the image presented to you is an "old image"' ...
        '\n\n Press any key to continue.'];

    text.welcomeText = line1;

    line2 = ['\n First we start with a practice run.'...
        '\n\n Remember press "5"-key once you think the image presented to'...
        '\n you is an old one. Otherwise if you think the image presented to you' ...
        '\n is a new one press the "4"-key.' ...
        '\n'...
        '\n\n All images are presented for 3s to you. For 1s you will see a blank space.'...
        '\n During that time please keep your eyes fixated on the black dot.'...
        '\n\n Press any key to continue.'];

    text.introductionText1 = line2;

    line3 = ['\n Practice run'...
        '\n '...
        '\n You will see 10 images, 3 of them are presented twice, so you '...
        '\n will get presented three "old images".If you recognize the old images,'...
        '\n please press "5". Otherwise if you think it is an new image please press "4".'...
        '\n\n Please fixate your eyes on the black dot, during the 1s blank space. '...
        '\n After the fixation time you will see the next picture.' ...
        '\n\n Press any key to continue.'];

    text.introductionText2 = line3;

    %%%%% text.endofBlock

    if any(currentBlockNumber == [1,2,3,4])

        line4 = ['\n Thanks for your attention.'...
            '\n\n Now take some time for a break and come outside of the experimental room.'...
            '\n Take the time you need.'...
            '\n If you have any questions feel free to ask.'...
            '\n\n Press any key to end the current block and save the data.'];
    end

    %% Adapt to amount of block numbers (stored in n_blocks)
    if currentBlockNumber == n_blocks
        line4 = ['\n Congratulations you completed the experiment.'...
            '\n If you have any questions feel free to ask.'...
            '\n\n Press any key to end the experiment and save the data.'];
    end

    text.endOfBlock = line4;


elseif currentLanguage == "German"


    line1 = ['\n Willkommen zu diesem Experiment.'...
        '\n\n In diesem Experiment werden Ihnen Bilder für jeweils 3 Sekunden präsentiert.'...
        '\n Einige der Bilder werden mehrmals gezeigt. Ihre Aufgabe ist es zu entscheiden, ' ...
        '\n ob das Ihnen gezeigte Bild ein neues Bild ist'...
        '\n (Ihnen innerhalb dieses Experiments noch nicht gezeigt wurde)'...
        '\n oder ein altes Bild ist (Ihnen bereits in diesem Experiment gezeigt wurde).'...
        '\n Drücken Sie die "4"-Taste mit Ihrem rechten Zeigefinger, wenn Sie denken das' ...
        '\n Ihnen präsentierte Bild ist ein "neues Bild". ' ...
        '\n Drücken Sie die "5"-Taste mit Ihrem rechten Mittelfinger, ' ...
        '\n wenn Sie denken das Ihnen präsentierte Bild ist ein "altes Bild".' ...
        '\n\n Drücken Sie eine beliebige Taste, um fortzufahren.'];

    text.welcomeText = line1;

    line2 = ['\n Wir beginnen mit einem Übungsdurchlauf .'...
        '\n\n Drücken Sie die "5"-Taste, wenn Sie ein "altes Bild" sehen.' ...
        ' \nDrücken Sie die "4"-Taste, wenn Sie ein "neues Bild" sehen.'...
        '\n'...
        '\n\n Alle Bilder werden Ihnen für 3 Sekunden präsentiert.' ...
        '\n Für eine Sekunde sehen Sie ein Fixationskreuz.'...
        '\n Bitte fixieren Sie dieses für die Darbietungsdauer.'...
        '\n\n Drücken Sie eine beliebige Taste, um fortzufahren.'];

    text.introductionText1 = line2;

    line3 = ['\n Übungsdurchlauf'...
        '\n '...
        '\n Sie werden zehn Bilder sehen, drei davon werden Ihnen wiederholt präsentiert. '...
        '\n Also werden Ihnen "alte Bilder" präsentiert. Wenn Sie ein "altes Bild" erkennen,'...
        '\n drücken Sie die "5"-Taste. Andernfalls, wenn Sie denken das Ihnen präsentierte Bild ' ...
        '\n ist neu, drücken Sie die"4"-Taste.'...
        '\n\n Bitte fixieren Sie das Fixationskreuz zwischen der Präsentation der unterschiedlichen Bilder. '...
        '\n\n Drücken Sie eine beliebige Taste, um fortzufahren.'];

    text.introductionText2 = line3;

    %%%%% text.endofBlock

    if any(currentBlockNumber == [1,2,3,4])

        line4 = ['\n Vielen Dank für Ihre Aufmerksamkeit.'...
            '\n\n Nehmen Sie sich jetzt bitte ein wenig Zeit für eine Pause und' ...
            '\n verlassen den Experimentalraum. '...
            '\n Nehmen Sie sich die Zeit, die Sie brauchen.'...
            '\n Wenn Sie Fragen haben, kontaktieren Sie den Versuchsleiter.'...
            '\n\n Drücken Sie eine beliebige Taste, um den Block abzuschließen und die Daten zu speichern.'];
    end

    %% Adapt to amount of block numbers (stored in n_blocks)
    if currentBlockNumber == n_blocks
        line4 = ['\n Herzlichen Glückwunsch, Sie haben das Experiment absolviert.'...
            '\n Falls Sie Fragen haben, kontaktieren Sie den Versuchsleiter.'...
            '\n\n Drücken Sie eine beliebige Taste, um das Experiment abzuschließen und die Daten zu speichern.'];
    end

    text.endOfBlock = line4;

end
